### ISSUE TITLE
Can't use Mekanism bronze for compressed bronze in the rolling machine

### ISSUE THREAD

**Issue by MadMax-XIII** [ChatFawkes/Flux-Galaxy#2]
According to your Minetweaker scripts, only the bronze from Forestry, Tinker Construct and Thermal Foundation can be used to make compressed bronze in the rolling machine, not the Mekanism version.

BTW, in case you're not already aware and following, [here](https://github.com/jaredlll08/ModTweaker2/issues/64) is the ModTweaker issue concerning the oredict problem with the rolling machine.

**Comment by ChatFawkes** [comment]
Yah I tried using ore dictionary months ago when I first was making all these recipes, but as you see in that issue it's never worked properly. I'll go ahead and add the Mekanism bronze recipes. Main reason I didn't just add all mods' bronze ingots in the first place is because I assumed most people would only use Thermal Foundation stuff.
